"""Static model catalog with known, valid model IDs and full metadata.

This is the authoritative data source for the /models command display.
Keys MUST match PROVIDER_REGISTRY keys (cs.Provider enum values).
"""

from . import constants as cs
from .types_defs import ModelInfo

MODEL_CATALOG: dict[str, list[ModelInfo]] = {
    cs.Provider.GOOGLE: [
        ModelInfo(
            provider="google",
            model_id="gemini-2.5-pro",
            display_name="Gemini 2.5 Pro",
            context_window=1048576,
            description="Advanced reasoning",
            requires_api_key=True,
            is_local=False,
            pricing_tier="medium",
        ),
        ModelInfo(
            provider="google",
            model_id="gemini-2.5-flash",
            display_name="Gemini 2.5 Flash",
            context_window=1048576,
            description="Fast responses",
            requires_api_key=True,
            is_local=False,
            pricing_tier="low",
        ),
        ModelInfo(
            provider="google",
            model_id="gemini-1.5-pro",
            display_name="Gemini 1.5 Pro",
            context_window=2097152,
            description="Balanced performance",
            requires_api_key=True,
            is_local=False,
            pricing_tier="medium",
        ),
        ModelInfo(
            provider="google",
            model_id="gemini-1.5-flash",
            display_name="Gemini 1.5 Flash",
            context_window=1048576,
            description="Cost-effective",
            requires_api_key=True,
            is_local=False,
            pricing_tier="low",
        ),
    ],
    cs.Provider.OPENAI: [
        ModelInfo(
            provider="openai",
            model_id="gpt-4o",
            display_name="GPT-4o",
            context_window=128000,
            description="Multimodal, fast",
            requires_api_key=True,
            is_local=False,
            pricing_tier="medium",
        ),
        ModelInfo(
            provider="openai",
            model_id="gpt-4o-mini",
            display_name="GPT-4o Mini",
            context_window=128000,
            description="Lightweight, economical",
            requires_api_key=True,
            is_local=False,
            pricing_tier="low",
        ),
        ModelInfo(
            provider="openai",
            model_id="gpt-4-turbo",
            display_name="GPT-4 Turbo",
            context_window=128000,
            description="High intelligence",
            requires_api_key=True,
            is_local=False,
            pricing_tier="high",
        ),
        ModelInfo(
            provider="openai",
            model_id="gpt-4",
            display_name="GPT-4",
            context_window=8192,
            description="Legacy model, limited context",
            requires_api_key=True,
            is_local=False,
            pricing_tier="high",
        ),
        ModelInfo(
            provider="openai",
            model_id="gpt-3.5-turbo",
            display_name="GPT-3.5 Turbo",
            context_window=128000,
            description="Budget-friendly, legacy",
            requires_api_key=True,
            is_local=False,
            pricing_tier="low",
        ),
    ],
    cs.Provider.ANTHROPIC: [
        ModelInfo(
            provider="anthropic",
            model_id="claude-3-5-sonnet",
            display_name="Claude 3.5 Sonnet",
            context_window=200000,
            description="Best overall",
            requires_api_key=True,
            is_local=False,
            pricing_tier="medium",
        ),
        ModelInfo(
            provider="anthropic",
            model_id="claude-3-opus",
            display_name="Claude 3 Opus",
            context_window=200000,
            description="Maximum intelligence",
            requires_api_key=True,
            is_local=False,
            pricing_tier="high",
        ),
        ModelInfo(
            provider="anthropic",
            model_id="claude-3-sonnet",
            display_name="Claude 3 Sonnet",
            context_window=200000,
            description="Balanced legacy model",
            requires_api_key=True,
            is_local=False,
            pricing_tier="medium",
        ),
        ModelInfo(
            provider="anthropic",
            model_id="claude-3-haiku",
            display_name="Claude 3 Haiku",
            context_window=200000,
            description="Fastest responses",
            requires_api_key=True,
            is_local=False,
            pricing_tier="low",
        ),
        ModelInfo(
            provider="anthropic",
            model_id="claude-2.1",
            display_name="Claude 2.1",
            context_window=200000,
            description="Legacy, long context",
            requires_api_key=True,
            is_local=False,
            pricing_tier="medium",
        ),
        ModelInfo(
            provider="anthropic",
            model_id="claude-2.0",
            display_name="Claude 2.0",
            context_window=100000,
            description="Legacy, shorter context",
            requires_api_key=True,
            is_local=False,
            pricing_tier="low",
        ),
    ],
    cs.Provider.AZURE: [
        ModelInfo(
            provider="azure",
            model_id="gpt-4o",
            display_name="GPT-4o (Azure)",
            context_window=128000,
            description="Multimodal, fast",
            requires_api_key=True,
            is_local=False,
            pricing_tier="medium",
        ),
        ModelInfo(
            provider="azure",
            model_id="gpt-4o-mini",
            display_name="GPT-4o Mini (Azure)",
            context_window=128000,
            description="Lightweight, economical",
            requires_api_key=True,
            is_local=False,
            pricing_tier="low",
        ),
        ModelInfo(
            provider="azure",
            model_id="gpt-4-turbo",
            display_name="GPT-4 Turbo (Azure)",
            context_window=128000,
            description="High intelligence",
            requires_api_key=True,
            is_local=False,
            pricing_tier="high",
        ),
    ],
    cs.Provider.OLLAMA: [
        ModelInfo(
            provider="ollama",
            model_id="llama3.2",
            display_name="Llama 3.2",
            context_window=8192,
            description="Default local model",
            requires_api_key=False,
            is_local=True,
            pricing_tier="free",
        ),
        ModelInfo(
            provider="ollama",
            model_id="llama3.1",
            display_name="Llama 3.1",
            context_window=128000,
            description="Extended context",
            requires_api_key=False,
            is_local=True,
            pricing_tier="free",
        ),
        ModelInfo(
            provider="ollama",
            model_id="mistral-nemo",
            display_name="Mistral Nemo",
            context_window=128000,
            description="High performance",
            requires_api_key=False,
            is_local=True,
            pricing_tier="free",
        ),
        ModelInfo(
            provider="ollama",
            model_id="gemma2",
            display_name="Gemma 2",
            context_window=128000,
            description="Google's lightweight model",
            requires_api_key=False,
            is_local=True,
            pricing_tier="free",
        ),
        ModelInfo(
            provider="ollama",
            model_id="qwen2",
            display_name="Qwen 2",
            context_window=128000,
            description="Alibaba's multilingual model",
            requires_api_key=False,
            is_local=True,
            pricing_tier="free",
        ),
        ModelInfo(
            provider="ollama",
            model_id="phi3",
            display_name="Phi 3",
            context_window=128000,
            description="Microsoft's compact model",
            requires_api_key=False,
            is_local=True,
            pricing_tier="free",
        ),
    ],
}

PROVIDER_DISPLAY_NAMES: dict[str, str] = {
    cs.Provider.GOOGLE: "Google AI",
    cs.Provider.OPENAI: "OpenAI",
    cs.Provider.ANTHROPIC: "Anthropic",
    cs.Provider.AZURE: "Azure OpenAI",
    cs.Provider.OLLAMA: "Ollama (Local)",
}
