#!/usr/bin/env python3
"""Generate Pydantic models from JSON Schema.

This script runs datamodel-codegen to generate Pydantic models from
the canonical JSON Schema at codebase_rag/schema.json.

Usage:
    python scripts/generate_schemas.py

The generated models are written to codebase_rag/schemas/ingestion.py
and should not be manually edited.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def main() -> int:
    """Generate Pydantic models from JSON Schema."""
    schema_path = Path("codebase_rag/schema.json")
    output_path = Path("codebase_rag/schemas/ingestion.py")

    if not schema_path.exists():
        print(f"Error: Schema file not found: {schema_path}", file=sys.stderr)
        return 1

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate models using datamodel-codegen
    result = subprocess.run(
        [
            "datamodel-codegen",
            "--input", str(schema_path),
            "--output", str(output_path),
            "--input-file-type", "jsonschema",
            "--output-model-type", "pydantic_v2.BaseModel",
            "--use-union-operator",
            "--target-python-version", "3.12",
            "--disable-timestamp",
            "--use-standard-collections",
            "--strict-nullable",
            "--use-schema-description",
            "--use-field-description",
            "--class-name", "IngestionPayload",
            "--wrap-string-literal",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"Error: {result.stderr}", file=sys.stderr)
        return 1

    # Add header comment to generated file
    if output_path.exists():
        content = output_path.read_text()
        header = '''"""
Auto-generated Pydantic models from JSON Schema.

DO NOT EDIT MANUALLY. This file is generated by scripts/generate_schemas.py.
To update models, modify codebase_rag/schema.json and run:
    python scripts/generate_schemas.py

Generated from: codebase_rag/schema.json
"""

'''
        output_path.write_text(header + content)

    print(f"Generated {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
