"""
Auto-generated Pydantic models from JSON Schema.

DO NOT EDIT MANUALLY. This file is generated by scripts/generate_schemas.py.
To update models, modify codebase_rag/schema.json and run:
    python scripts/generate_schemas.py

Generated from: codebase_rag/schema.json
"""

# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class Metadata(BaseModel):
    """
    Optional metadata for the dataset
    """

    model_config = ConfigDict(
        extra='allow',
    )
    dataset_id: str | None = None
    """
    Unique identifier for this dataset (used for deduplication and bulk operations)
    """
    source: str | None = None
    """
    Source attribution for the data
    """
    created_at: AwareDatetime | None = None
    """
    Timestamp when the dataset was created (ISO 8601)
    """


class Entity(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str | None = None
    """
    Unique entity ID (auto-generated if not provided)
    """
    name: constr(min_length=1)
    """
    Human-readable name of the entity (required, used for deduplication if no ID)
    """
    type: str | None = None
    """
    Entity type or category (e.g., 'Person', 'Concept', 'Role')
    """
    labels: list[str] | None = None
    """
    Labels to apply to the graph node
    """
    properties: dict[str, Any] | None = None
    """
    Arbitrary key-value properties
    """


class Relationship(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    source: constr(min_length=1)
    """
    Source entity name or ID
    """
    target: constr(min_length=1)
    """
    Target entity name or ID
    """
    relationship: constr(min_length=1)
    """
    Relationship type (e.g., 'IS_A', 'PART_OF', 'causes')
    """
    category: str | None = None
    """
    Relationship category for verb inference and visualization. One of: CAUSAL, HIERARCHICAL, COMPOSITIONAL, CONTEXTUAL, ATTRIBUTIVE, SEQUENTIAL, COMPARATIVE, ANALOGICAL. Auto-inferred from relationship type if not provided.
    """
    properties: dict[str, Any] | None = None
    """
    Arbitrary key-value properties (e.g., confidence, explanation)
    """


class IngestionPayload(BaseModel):
    """
    Minimal schema for ingesting entities and relationships into Memgraph. Designed for maximum flexibility - users control display format, naming conventions, and content structure.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    metadata: Metadata | None = None
    """
    Optional metadata for the dataset
    """
    entities: list[Entity]
    """
    Graph nodes to ingest. Each entity must have a name. All other fields are optional.
    """
    relationships: list[Relationship] | None = None
    """
    Graph relationships between entities. Each relationship requires source, target, and type.
    """
